version: "3.9"

services:
  postgres-dev:
    image: postgres:17
    container_name: wallet-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - wallet-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wallet-service
    restart: always
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-dev:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: ${DDL_AUTO}
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_LIQUIBASE_CHANGE_LOG: classpath:db/migration/db.changelog-master.yaml

      SPRINGDOC_SWAGGER_UI_ENABLED: ${SWAGGER_ENABLED}
      SPRINGDOC_API_DOCS_ENABLED: ${SWAGGER_ENABLED}
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      postgres-dev:
        condition: service_healthy

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8082:8080"
    depends_on:
      - postgres-dev

volumes:
  wallet-db-data:
